baseURL = "https://ccdd-hugo-2022.netlify.app"
languageCode = "en-us"
theme = "agen-hugo"
title = "Web Design | chrisConnellyDotDev"
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.footer]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.footer]]
URL = "service"
name = "Service"
weight = 2
[[menu.footer]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "blog"
name = "Blog"
parent = "pages"
weight = 1
[[menu.main]]
URL = "faqs"
name = "FAQs"
parent = "pages"
weight = 2
[[menu.main]]
URL = "career"
name = "Career"
parent = "pages"
weight = 3
[[menu.main]]
URL = "pricing"
name = "Pricing"
parent = "pages"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[[menu.main]]
hasChildren = true
name = "pages"
weight = 4
[[menu.main]]
URL = "projects"
name = "Projects"
weight = 3
[[menu.main]]
URL = "service"
name = "Service"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[params]
logo = "images/logo.webp"
home = "Home"
# Meta data
description = "This is meta description"
author = "chrisConnellyDotDev"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCDUrJQixpBNVKD-lJcmLHRRfkw8dXRccs&libraries=places"
mapLatitude = "51.100159"
mapLongitude = "-113.950508"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "UA-168676797-1"
  # Preloader
  [params.preloader]
  enable = true

  ############################# Footer Start ###########################

  # footer about
  [params.footer.about]
  about = "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae, odit? Sapiente et temporibus qui corporis veritatis ipsa culpa, numquam id."

  # contact form
  [params.form]
  formAction = "#"

  # copyright
  [params.copyright]
  copyright = "Copyright &copy; 2019 a theme by [themefisher.com](https://themefisher.com)"

  ######################### Social site ##############################
  [[params.social]]
  icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
  link = "https://facebook.com/chrisconnellydotdev"
  
  [[params.social]]
  icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
  link = "#"
  
  [[params.social]]
  icon = "ti-github" # themify icon pack https://themify.me/themify-icons
  link = "https://github.com/teamallnighter"
  
  [[params.social]]
  icon = "ti-instagram" # themify icon pack https://themify.me/themify-icons
  link = "#"
