baseURL = "https://ccdd-hugo-2022.netlify.app"
languageCode = "en-us"
theme = "agen-hugo"
title = "Web Design | chrisConnellyDotDev"
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.footer]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.footer]]
URL = "service"
name = "Service"
weight = 2
[[menu.footer]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "blog"
name = "Blog"
parent = "pages"
weight = 1
[[menu.main]]
URL = "faqs"
name = "FAQs"
parent = "pages"
weight = 2
[[menu.main]]
URL = "career"
name = "Career"
parent = "pages"
weight = 3
[[menu.main]]
URL = "pricing"
name = "Pricing"
parent = "pages"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[[menu.main]]
hasChildren = true
name = "pages"
weight = 4
[[menu.main]]
URL = "projects"
name = "Projects"
weight = 3
[[menu.main]]
URL = "service"
name = "Service"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[params]
author = "Themefisher"
description = "This is meta description"
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
googleAnalitycsID = "Your ID"
home = "Home"
logo = "images/logo.png"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
[params.copyright]
copyright = "Copyright &copy; 2019 a theme by [themefisher.com](https://themefisher.com)"
[params.footer.about]
about = "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae, odit? Sapiente et temporibus qui corporis veritatis ipsa culpa, numquam id."
[params.form]
formAction = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"
[[params.plugins.css]]
URL = "plugins/card-slider/css/style.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
URL = "plugins/counto/apear.js"
[[params.plugins.js]]
URL = "plugins/counto/counTo.js"
[[params.plugins.js]]
URL = "plugins/card-slider/js/card-slider-min.js"
[[params.plugins.js]]
URL = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-github"
link = "#"
[[params.social]]
icon = "ti-instagram"
link = "#"
